### ISSUE TITLE
Drive letters don't work on Windows

### ISSUE THREAD

**Issue by Quiescent** [microamp/helm-rg#2]
Hi there!

I like this package!
To my mind, it's a simple alternative to the other package for `ripgrep` via `helm`.

Do you welcome contributions?

It seems like it doesn't work on Windows because it splits on colon and windows has drive letters.
I've forked your repo and patched it which appears to have fixed the problem.

Are you interested in a PR?

**Comment by microamp** [comment]
Hi. Thanks for the kind words. It's a very simple package as you can tell.

I don't have a Windows machine at the moment, and I no longer use helm (I replaced it with ivy a while ago). However, I'm interested in your PR in case someone else finds it useful in the future. Thanks.

**Comment by Quiescent** [comment]
Great!
I've created #3, which includes another minor fix (adds line numbers to hits) in addition to the drive letter fix.
WDYT? :)

**Comment by microamp** [comment]
Fixed via #3
